# Get real data

In [1]:
import pandas as pd

from pyreporter.utils import get_metadata, get_sname, get_plotdata
from pyreporter.meta_repository import MetaRepository

from pyreporter.limer import limer_connect, limer_list_surveys, limer_responses, limer_release, limer_n, limer_SIDs

In [2]:
snr = "0001"
stype = "gy"
audience = "sus"      
ubb = False                   
ganztag = False
has_N = ["sus", "elt"]

In [3]:
meta_repo = MetaRepository()
meta_templates = meta_repo.meta_templates
meta_reports = meta_repo.meta_reports
meta_snames = meta_repo.meta_snames


meta_sets = meta_repo.meta_sets

In [4]:
sname_meta = get_sname(
    meta_snames=meta_snames,
    snr = snr
    )

print("\n Report for:", sname_meta)

 Report for: Leibniz-Gymnasium Altdorf

In [5]:
limer_connect()
sids_df = limer_SIDs(snr=snr, ubb=ubb)
sid = sids_df["sid"]
print("\nReport template:", sid[0])

Report template: 252356

In [6]:
sids_df.head()

,sid,surveyls_title,startdate,expires,active,snr,completed_responses
0,252356,0001_202425_bfr_allg_gy_elt_00_2022_p1,2025-12-01 16:07:00,2025-12-19 16:07:00,Y,0001,10
1,251539,0001_202425_bfr_allg_gy_sus_00_2022_p1,NaN,2025-09-03 11:26:00,Y,0001,10
2,453143,0001_202425_bfr_allg_gy_leh_00_2022_p1,2024-09-02 14:38:00,2025-09-03 11:26:00,Y,0001,10

In [7]:
print(sids_df.sid)

0    252356
1    251539
2    453143
Name: sid, dtype: str

In [8]:
df = limer_responses(
    iSurveyID= sid[0],
    sCompletionStatus="complete"
)
    
limer_release()

print("\nData downloaded:", df.head())

Data downloaded:   id           submitdate lastpage startlanguage        seed  E01[B131W124E]  \
0  1  2024-08-28 10:16:31        6            de  1440250481  stimme eher zu
1  2  2024-08-28 10:16:31        6            de  1991639343      weiß nicht
2  3  2024-08-28 10:16:31        6            de  1327331583    teils, teils
3  4  2024-08-28 10:16:31        6            de  1095599110    teils, teils
4  5  2024-08-28 10:16:31        6            de  1595537486    teils, teils

            E01[B132a]            E01[B132c]            E01[B133b]  \
0  stimme gar nicht zu      stimme völlig zu  stimme eher nicht zu
1         teils, teils            weiß nicht      stimme völlig zu
2       stimme eher zu            weiß nicht            weiß nicht
3           weiß nicht  stimme eher nicht zu            weiß nicht
4  stimme gar nicht zu          teils, teils        stimme eher zu

        E02[B334W125a]  ...             E05[B112]           E05[D314a]  \
0         teils, teils  ...  stimme eher nicht zu  stimme gar nicht zu
1  stimme gar nicht zu  ...   stimme gar nicht zu  stimme gar nicht zu
2           weiß nicht  ...   stimme gar nicht zu         teils, teils
3       stimme eher zu  ...      stimme völlig zu       stimme eher zu
4     stimme völlig zu  ...            weiß nicht           weiß nicht

             E05[D314b]              Zuf[Z1E]              Zuf[Z2E]  \
0          teils, teils  gar nicht zufrieden   eher nicht zufrieden
1            weiß nicht            weiß nicht        sehr zufrieden
2   stimme gar nicht zu  eher nicht zufrieden        sehr zufrieden
3  stimme eher nicht zu            weiß nicht        eher zufrieden
4        stimme eher zu        eher zufrieden        sehr zufrieden

               Zuf[Z3E]              Zuf[Z4E]              Zuf[Z5E]  \
0        sehr zufrieden        eher zufrieden            weiß nicht
1        eher zufrieden  gar nicht zufrieden   eher nicht zufrieden
2  eher nicht zufrieden  eher nicht zufrieden            weiß nicht
3  gar nicht zufrieden         sehr zufrieden  eher nicht zufrieden
4            weiß nicht            weiß nicht            weiß nicht

               Zuf[Z6E]              Zuf[Z7E]
0  eher nicht zufrieden        sehr zufrieden
1  eher nicht zufrieden        eher zufrieden
2            weiß nicht  gar nicht zufrieden
3        eher zufrieden        eher zufrieden
4  eher nicht zufrieden  gar nicht zufrieden

[5 rows x 34 columns]

In [14]:
from pyreporter.utils import get_data
realdf = get_data(id = "251539", surveyls_title = "Bla", ubb = False)
realdf.head()

      sid surveyls_title id   vars vals  vars_old
0  251539            Bla  1  tpage   15  lastpage
1  251539            Bla  2  tpage   15  lastpage
2  251539            Bla  3  tpage   15  lastpage
3  251539            Bla  4  tpage   15  lastpage
4  251539            Bla  5  tpage   15  lastpage

In [15]:
report_meta = get_metadata(
        meta_templates=meta_templates,
        meta_reports=meta_reports,
        school=stype,
        audience=audience,
        ub=ubb,
        gt=ganztag,
        data_avail=has_N
    )

#plots = report_meta['plot'] 
print("\nMeta data:", report_meta)

Meta data: {'report': 'rpt_sus_p1', 'meta': ['A11', 'A12', 'A13', 'A21', 'A22', 'A32', 'A41', 'A42', 'A43', 'A51', 'A52', 'A53', 'A61', 'A63', 'A64', 'B11', 'B12', 'B13', 'B21', 'B22', 'B31', 'B32', 'B33', 'W12', 'W14', 'W24', 'W25', 'W26', 'W2sus', 'ZS']}

In [16]:
sids_df.columns

Index(['sid', 'surveyls_title', 'startdate', 'expires', 'active', 'snr',
       'completed_responses'],
      dtype='str')

In [17]:
print(realdf.columns.tolist())

['sid', 'surveyls_title', 'id', 'vars', 'vals', 'vars_old']

In [23]:
print(realdf["vars"].unique())

<StringArray>
[     'tpage', 'rtlanguage',          'd',         'gy',       'B132',
       'B133',  'B131W124A',  'B131W124B',  'B131W124C',       'B123',
       'B312',       'B122',       'B331',   'B321W261',       'B332',
       'B111',       'B113',       'B112',      'W2use',  'A635W245a',
   'B324W264',   'A423W243',  'A635W245b',   'B322W262',   'B323W263',
   'B325W265',   'A324W242',      'B211A',      'B211B',       'B212',
      'B223a',      'B223b',      'B223c',      'B223d',           '',
      'A111A',      'A111B',      'A111C',      'A111D',       'A122',
      'A123A',      'A123B',      'A321A',   'A131W121',   'A134W122',
      'A133A',      'A133B',       'A432',       'A431',   'A522W145',
       'A641',  'A526W255A',  'A526W255B',      'A211A',      'A211B',
       'A213',      'A221A',      'A221B',       'A644',       'A611',
       'A422',       'A421',       'A643',      'A321B',       'A411',
       'A531',       'A532',   'A515W143',       'A533',  'A535W254a',
  'A535W254b',       'A434',       'A433',   'A521W144',      'A631A',
       'A633',       'A634',      'A631B',       'A642',       'A632',
        'Z1S',        'Z2S',        'Z3S',        'Z4S',        'Z5S',
    'mitdate']
Length: 86, dtype: str

In [22]:
plotdf = get_plotdata(
    data = realdf,
    report_name = "rpt_sus_p1",
    plot_name = "A11",
    audience = audience)

plotdf.head()

,vars,vals,label_short,anz,p,label_n,set
0,A111A,weiß nicht,"Die Lehrkraft bekommt mit, was in der Klasse a...",2,20.0,20%,set01
1,A111A,stimmt ganz genau,"Die Lehrkraft bekommt mit, was in der Klasse a...",1,10.0,10%,set01
2,A111A,stimmt eher,"Die Lehrkraft bekommt mit, was in der Klasse a...",2,20.0,20%,set01
3,A111A,stimmt zum Teil,"Die Lehrkraft bekommt mit, was in der Klasse a...",2,20.0,20%,set01
4,A111A,stimmt eher nicht,"Die Lehrkraft bekommt mit, was in der Klasse a...",2,20.0,20%,set01

In [24]:
print(df)

   id           submitdate lastpage startlanguage        seed  \
0   1  2024-08-28 10:16:31        6            de  1440250481
1   2  2024-08-28 10:16:31        6            de  1991639343
2   3  2024-08-28 10:16:31        6            de  1327331583
3   4  2024-08-28 10:16:31        6            de  1095599110
4   5  2024-08-28 10:16:31        6            de  1595537486
5   6  2024-08-28 10:16:31        6            de  1449546453
6   7  2024-08-28 10:16:31        6            de  1639902543
7   8  2024-08-28 10:16:31        6            de  1932106724
8   9  2024-08-28 10:16:31        6            de  1450964550
9  10  2024-08-28 10:16:31        6            de  1518709263

     E01[B131W124E]            E01[B132a]            E01[B132c]  \
0    stimme eher zu   stimme gar nicht zu      stimme völlig zu
1        weiß nicht          teils, teils            weiß nicht
2      teils, teils        stimme eher zu            weiß nicht
3      teils, teils            weiß nicht  stimme eher nicht zu
4      teils, teils   stimme gar nicht zu          teils, teils
5  stimme völlig zu   stimme gar nicht zu        stimme eher zu
6    stimme eher zu  stimme eher nicht zu      stimme völlig zu
7      teils, teils            weiß nicht  stimme eher nicht zu
8        weiß nicht            weiß nicht          teils, teils
9        weiß nicht   stimme gar nicht zu        stimme eher zu

             E01[B133b]       E02[B334W125a]  ...             E05[B112]  \
0  stimme eher nicht zu         teils, teils  ...  stimme eher nicht zu
1      stimme völlig zu  stimme gar nicht zu  ...   stimme gar nicht zu
2            weiß nicht           weiß nicht  ...   stimme gar nicht zu
3            weiß nicht       stimme eher zu  ...      stimme völlig zu
4        stimme eher zu     stimme völlig zu  ...            weiß nicht
5      stimme völlig zu       stimme eher zu  ...      stimme völlig zu
6   stimme gar nicht zu     stimme völlig zu  ...            weiß nicht
7  stimme eher nicht zu           weiß nicht  ...   stimme gar nicht zu
8          teils, teils           weiß nicht  ...      stimme völlig zu
9  stimme eher nicht zu  stimme gar nicht zu  ...  stimme eher nicht zu

            E05[D314a]            E05[D314b]              Zuf[Z1E]  \
0  stimme gar nicht zu          teils, teils  gar nicht zufrieden
1  stimme gar nicht zu            weiß nicht            weiß nicht
2         teils, teils   stimme gar nicht zu  eher nicht zufrieden
3       stimme eher zu  stimme eher nicht zu            weiß nicht
4           weiß nicht        stimme eher zu        eher zufrieden
5         teils, teils            weiß nicht        eher zufrieden
6           weiß nicht      stimme völlig zu  eher nicht zufrieden
7     stimme völlig zu        stimme eher zu        eher zufrieden
8         teils, teils      stimme völlig zu  eher nicht zufrieden
9     stimme völlig zu            weiß nicht  eher nicht zufrieden

               Zuf[Z2E]              Zuf[Z3E]              Zuf[Z4E]  \
0  eher nicht zufrieden        sehr zufrieden        eher zufrieden
1        sehr zufrieden        eher zufrieden  gar nicht zufrieden
2        sehr zufrieden  eher nicht zufrieden  eher nicht zufrieden
3        eher zufrieden  gar nicht zufrieden         sehr zufrieden
4        sehr zufrieden            weiß nicht            weiß nicht
5        sehr zufrieden  eher nicht zufrieden  gar nicht zufrieden
6  eher nicht zufrieden  eher nicht zufrieden  eher nicht zufrieden
7            weiß nicht            weiß nicht  eher nicht zufrieden
8        sehr zufrieden            weiß nicht            weiß nicht
9        eher zufrieden  eher nicht zufrieden        eher zufrieden

               Zuf[Z5E]              Zuf[Z6E]              Zuf[Z7E]
0            weiß nicht  eher nicht zufrieden        sehr zufrieden
1  eher nicht zufrieden  eher nicht zufrieden        eher zufrieden
2            weiß nicht            weiß nicht  gar nicht zufrieden
3  eher nicht zufrieden        eher zufrieden        eher zufrieden
4            weiß nicht  eher nicht zufrieden  gar nicht zufrieden
5        sehr zufrieden  gar nicht zufrieden             weiß nicht
6        sehr zufrieden            weiß nicht        sehr zufrieden
7        eher zufrieden  gar nicht zufrieden   eher nicht zufrieden
8  eher nicht zufrieden        eher zufrieden  eher nicht zufrieden
9  eher nicht zufrieden        sehr zufrieden        sehr zufrieden

[10 rows x 34 columns]